apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: us-central1-docker.pkg.dev/golang-sre-devops-2024/sre-devops/python-portfolio:v1.0.1
        ports:
        - containerPort: 80
        env:
        - name: FLASK_RUN_PORT
          value: "80"